services:
  nas-video-converter:
    image: ghcr.io/ccawmiku/nas-video-converter:1.0.6
    container_name: nas-video-converter
    restart: unless-stopped
    ports:
      - "12012:12012"
    environment:
      PUID: "1026"
      PGID: "100"
      TZ: Asia/Shanghai
    volumes:
      - /volume2/docker/nas-video-converter/config:/config:rw
      # 每个一级子目录会作为网页中的独立映射根目录。媒体目录必须可写。
      - /volume1/video:/media/视频库:rw
      - /volume1/movie:/media/电影:rw
      # - /volume2/other:/media/其他目录:rw
    devices:
      - /dev/dri:/dev/dri
    security_opt:
      - no-new-privileges:true
